require 'faker'
require 'date'

puts "Clearing database..."
Application.destroy_all

Job.destroy_all

empl = User.all
empl.each do |e|
  e.image.purge
end
Employer.destroy_all

usr = User.all
usr.each do |u|
  u.image.purge
end
User.destroy_all
puts "Database cleared!"

companies = [
  { name: "Ubisoft", city: "Berlin", street: "Hardenbergstraße 32", postcode: 10623, domain: "ubisoft.com" },
  { name: "Electronic Arts", city: "Berlin", street: "Berliner Straße 116", postcode: 10713, domain: "ea.com" },
  { name: "Nintendo", city: "Frankfurt am Main", street: "Goldsteinstraße 235", postcode: 60528, domain: "nintendo.de" },
  { name: "Activision Blizzard", city: "Berlin", street: "Jägerstraße 32", postcode: 10117, domain: "activision.com" },
  { name: "343 Industries", city: "Berlin", street: "Storkower 32", postcode: 10407, domain: "343industries.com" },
  { name: "Bethesda Game Studios", city: "Frankfurt am Main", street: "Goldsteinstraße 2", postcode: 10127, domain: "bethesda.net" },
  { name: "Epic Games", city: "Berlin", street: "Unter den Linden 300", postcode: 10317, domain: "epicgames.com" },
  { name: "Guerrilla Games", city: "Berlin", street: "Rudi-Dutschke-Straße 26", postcode: 10969, domain: "guerrilla-games.com" },
  { name: "Riot Games", city: "Frankfurt am Main", street: "Vossstrasse 23", postcode: 10117, domain: "riotgames.com" },
  { name: "Santa Monica Studio", city: "Berlin", street: "Friedrichstraße 219", postcode: 10969, domain: "sms.playstation.com" },
  { name: "Square Enix", city: "Berlin", street: "Urbanstraße 70A", postcode: 10200, domain: "square-enix-games.com" },
  { name: "Fatshark", city: "Berlin", street: "Weinmeisterstraße 12", postcode: 10178, domain: "fatshark.se" },
  { name: "Red Hook", city: "Berlin", street: "Strausberger Pl. 112", postcode: 49600, domain: "redhookgames.com" }
  ]

recruiters = []
13.times do |index|
  recruiters[index] = "#{Faker::Name.first_name} #{Faker::Name.last_name}"
end

puts "Creating users..."
password = "123456"
hinnerk = User.create!({ email: "hinnerk@nerdadvisor.org", password: password, firstName: "Hinnerk", lastName: "Künnen", city: "Berlin", category: "Engineer", skills: ["Machine Learning", "Workflow Development", "Web Development", "Technical Documentation", "JavaScript", "React", "SQL", "Problem Solving", "Debugging", "Troubleshooting"],
  linkedin: "www.linkedin.com/in/hinnerkkuennen/", github: "https://github.com/hkuennen", desc: "Graduated with an Economics degree, I am a former IT Consultant looking for a new job as a Backend / Full Stack Developer and changing career paths.
  Also, I consider myself a Python enthusiast keen to learn a new programming language in the Web Development world and shaping the digital future. In my leisure time, you'll find me at Lerchen&Eulen drinking margaritas.", role: "Job Seeker", level: 1, xp: 0 })
hinnerk.image.attach(io: File.open("app/assets/images/users/hinnerk.jpg"), filename: "hinnerk.jpg", content_type: "image/jpg")

aj = User.create!({ email: "aj@nerdadvisor.org", password: password, firstName: "Arjuna", lastName: "Sath", city: "Berlin", category: "Artist", skills: ["Sketch Art", "2D Art", "Graphic Design", "Photoshop", "AutoCAD"],
  linkedin: "www.linkedin.com/in/ajsath/", github: "https://github.com/ajsath", desc: "A marketing & business development veteran with 10+ years of service. Given my computer science background and continuation of full stack development, I strive to have a
  strong understanding of multiple departments (Product, Marketing, Sales, Coding, Design, Business Development, etc.) to better manage projects and understand through first-hand experience, the responsibilities/duties that my peers & colleagues carry.", role: "Job Seeker", level: 1, xp: 0 })
aj.image.attach(io: File.open("app/assets/images/users/aj.jpg"), filename: "aj.jpg", content_type: "image/jpg")

adi = User.create!({ email: "adi@nerdadvisor.org", password: password, firstName: "Luthfi Aditya", lastName: "Pratomo", city: "Berlin", category: "Artist", skills: ["Web Development", "Front-end", "Product Design", "Graphic Design", "Product Marketing", "Problem Solving", "Debugging", "Prototyping"],
  linkedin: "https://www.linkedin.com/in/luthfipratomo/", github: "https://github.com/Lapratomo24", desc: "I was a Marketing Manager until 30.09. I decided to resign to be able to join Le Wagon and learn how to code. I would like to switch my career and become a web developer.", role: "Job Seeker", level: 1, xp: 0 })
adi.image.attach(io: File.open("app/assets/images/users/adi.jpg"), filename: "adi.jpg", content_type: "image/jpg")

juan = User.create!({ email: "juan@nerdadvisor.org", password: password, firstName: "Juan",lastName: "Hurtado", city: "Berlin", category: "Sound", skills: ["Web Development", "Singing", "Musician", "Voice Acting", "Theatre", "Writer", "Actor", "Problem Solving", "Debugging"], github: "https://github.com/SUMAJU",
  desc: "My name is Juan, I'm 35 years old and I'm from Argentina. I am an actor, theatre director and writer. My wish is to be able to get a job with programming that allows me more independence.", role: "Job Seeker", level: 1, xp: 0 })
juan.image.attach(io: File.open("app/assets/images/users/juan.jpg"), filename: "juan.jpg", content_type: "image/jpg")
puts "Users created!"

users = User.all

puts "Creating employers..."
  f_name_0 = recruiters[0].split(" ").first
  l_name_0 = recruiters[0].split(" ").last
  ubisoft = Employer.create!({ companyName: companies[0][:name], city: companies[0][:city], street: companies[0][:street], postcode: companies[0][:postcode], market: "Videogames", recruiterFirstName: f_name_0, recruiterLastName: l_name_0, recruiterEmail: "#{f_name_0.downcase}.#{l_name_0.downcase}@#{companies[0][:domain]}" })
  ubisoft.image.attach(io: File.open("app/assets/images/employers/ubisoft.jpg"), filename: "ubisoft.jpg", content_type: "image/jpg")

  f_name_1 = recruiters[1].split(" ").first
  l_name_1 = recruiters[1].split(" ").last
  ea = Employer.create!({ companyName: companies[1][:name], city: companies[1][:city], street: companies[1][:street], postcode: companies[1][:postcode], market: "Videogames", recruiterFirstName: f_name_1, recruiterLastName: l_name_1, recruiterEmail: "#{f_name_1.downcase}.#{l_name_1.downcase}@#{companies[1][:domain]}" })
  ea.image.attach(io: File.open("app/assets/images/employers/ea.jpg"), filename: "ea.jpg", content_type: "image/jpg")

  f_name_2 = recruiters[2].split(" ").first
  l_name_2 = recruiters[2].split(" ").last
  nintendo = Employer.create!({ companyName: companies[2][:name], city: companies[2][:city], street: companies[2][:street], postcode: companies[2][:postcode], market: "Videogames", recruiterFirstName: f_name_2, recruiterLastName: l_name_2, recruiterEmail: "#{f_name_2.downcase}.#{l_name_2.downcase}@#{companies[2][:domain]}" })
  nintendo.image.attach(io: File.open("app/assets/images/employers/nintendo.jpg"), filename: "nintendo.jpg", content_type: "image/jpg")

  f_name_3 = recruiters[3].split(" ").first
  l_name_3 = recruiters[3].split(" ").last
  activision = Employer.create!({ companyName: companies[3][:name], city: companies[3][:city], street: companies[3][:street], postcode: companies[3][:postcode], market: "Videogames", recruiterFirstName: f_name_3, recruiterLastName: l_name_3, recruiterEmail: "#{f_name_3.downcase}.#{l_name_3.downcase}@#{companies[3][:domain]}" })
  activision.image.attach(io: File.open("app/assets/images/employers/activision.jpg"), filename: "activision.jpg", content_type: "image/jpg")

  f_name_4 = recruiters[4].split(" ").first
  l_name_4 = recruiters[4].split(" ").last
  industries = Employer.create!({ companyName: companies[4][:name], city: companies[4][:city], street: companies[4][:street], postcode: companies[4][:postcode], market: "Videogames", recruiterFirstName: f_name_4, recruiterLastName: l_name_4, recruiterEmail: "#{f_name_4.downcase}.#{l_name_4.downcase}@#{companies[4][:domain]}" })
  industries.image.attach(io: File.open("app/assets/images/employers/industries.jpg"), filename: "industries.jpg", content_type: "image/jpg")

  f_name_5 = recruiters[5].split(" ").first
  l_name_5 = recruiters[5].split(" ").last
  bethesda = Employer.create!({ companyName: companies[5][:name], city: companies[5][:city], street: companies[5][:street], postcode: companies[5][:postcode], market: "Videogames", recruiterFirstName: f_name_5, recruiterLastName: l_name_5, recruiterEmail: "#{f_name_5.downcase}.#{l_name_5.downcase}@#{companies[5][:domain]}" })
  bethesda.image.attach(io: File.open("app/assets/images/employers/bethesda.jpg"), filename: "bethesda.jpg", content_type: "image/jpg")

  f_name_6 = recruiters[6].split(" ").first
  l_name_6 = recruiters[6].split(" ").last
  epicGames = Employer.create!({ companyName: companies[6][:name], city: companies[6][:city], street: companies[6][:street], postcode: companies[6][:postcode], market: "Videogames", recruiterFirstName: f_name_6, recruiterLastName: l_name_6, recruiterEmail: "#{f_name_6.downcase}.#{l_name_6.downcase}@#{companies[6][:domain]}" })
  epicGames.image.attach(io: File.open("app/assets/images/employers/epicGames.jpg"), filename: "epicGames.jpg", content_type: "image/jpg")

  f_name_7 = recruiters[7].split(" ").first
  l_name_7 = recruiters[7].split(" ").last
  guerrilla = Employer.create!({ companyName: companies[7][:name], city: companies[7][:city], street: companies[7][:street], postcode: companies[7][:postcode], market: "Videogames", recruiterFirstName: f_name_7, recruiterLastName: l_name_7, recruiterEmail: "#{f_name_7.downcase}.#{l_name_7.downcase}@#{companies[7][:domain]}" })
  guerrilla.image.attach(io: File.open("app/assets/images/employers/guerrilla.jpg"), filename: "guerrilla.jpg", content_type: "image/jpg")

  f_name_8 = recruiters[8].split(" ").first
  l_name_8 = recruiters[8].split(" ").last
  riotGames = Employer.create!({ companyName: companies[8][:name], city: companies[8][:city], street: companies[8][:street], postcode: companies[8][:postcode], market: "Videogames", recruiterFirstName: f_name_8, recruiterLastName: l_name_8, recruiterEmail: "#{f_name_8.downcase}.#{l_name_8.downcase}@#{companies[8][:domain]}" })
  riotGames.image.attach(io: File.open("app/assets/images/employers/riotGames.jpg"), filename: "riotGames.jpg", content_type: "image/jpg")

  f_name_9 = recruiters[9].split(" ").first
  l_name_9 = recruiters[9].split(" ").last
  santaMonica = Employer.create!({ companyName: companies[9][:name], city: companies[9][:city], street: companies[9][:street], postcode: companies[9][:postcode], market: "Videogames", recruiterFirstName: f_name_9, recruiterLastName: l_name_9, recruiterEmail: "#{f_name_9.downcase}.#{l_name_9.downcase}@#{companies[9][:domain]}" })
  santaMonica.image.attach(io: File.open("app/assets/images/employers/santaMonica.jpg"), filename: "santaMonica.jpg", content_type: "image/jpg")

  f_name_10 = recruiters[10].split(" ").first
  l_name_10 = recruiters[10].split(" ").last
  squareEnix = Employer.create!({ companyName: companies[10][:name], city: companies[10][:city], street: companies[10][:street], postcode: companies[10][:postcode], market: "Videogames", recruiterFirstName: f_name_10, recruiterLastName: l_name_10, recruiterEmail: "#{f_name_10.downcase}.#{l_name_10.downcase}@#{companies[10][:domain]}" })
  squareEnix.image.attach(io: File.open("app/assets/images/employers/squareEnix.jpg"), filename: "squareEnix.jpg", content_type: "image/jpg")

  f_name_11 = recruiters[11].split(" ").first
  l_name_11 = recruiters[11].split(" ").last
  fatshark = Employer.create!({ companyName: companies[11][:name], city: companies[11][:city], street: companies[11][:street], postcode: companies[11][:postcode], market: "Videogames", recruiterFirstName: f_name_11, recruiterLastName: l_name_11, recruiterEmail: "#{f_name_11.downcase}.#{l_name_11.downcase}@#{companies[11][:domain]}" })
  fatshark.image.attach(io: File.open("app/assets/images/employers/fatshark.jpg"), filename: "fatshark.jpg", content_type: "image/jpg")

  f_name_12 = recruiters[12].split(" ").first
  l_name_12 = recruiters[12].split(" ").last
  redhook = Employer.create!({ companyName: companies[12][:name], city: companies[12][:city], street: companies[12][:street], postcode: companies[12][:postcode], market: "Videogames", recruiterFirstName: f_name_12, recruiterLastName: l_name_12, recruiterEmail: "#{f_name_12.downcase}.#{l_name_12.downcase}@#{companies[12][:domain]}" })
  redhook.image.attach(io: File.open("app/assets/images/employers/redhook.jpg"), filename: "redhook.jpg", content_type: "image/jpg")


puts "Employers created!"

employers = Employer.all

puts "Creating jobs..."
  Job.create!({ title: "Lead Game Developer (f/m/d)", desc: "As Lead Game Developer you will act in a project leadership capacity to help solve production or creative problems. You will be working closely with the Game Director & Creative Director. You are responsible for building design teams and collaborate with partners. The major focus areas of this position are people management, creativity, communication, problem solving and mitigation.", _type: "Fulltime", startDate: Date.new(2022,12,01), salary: 66000, city: ubisoft.city, user_id: hinnerk.id, employer_id: ubisoft.id, companySize: "1000+", category: "Developer", onsite: "On-Site" })

  Job.create!({ title: "Junior Voice Artist", desc: "At EA we strive to tell stories within existing and new video game worlds. Want to join us in voicing our next project? You're in luck! We're looking to expand our talent pool of great male actors to work with our lead Creative Director on the voice of our next project. You can work remotely!!! you will be able to be with your family and enjoy your warm home...", _type: "Working Student", startDate: Date.new(2022,12,01), salary: 60000, city: ea.city, user_id: aj.id, employer_id: ea.id, companySize: "1000+", category: "Artist", onsite: "Hybrid" })

  Job.create!({ title: "German Voice Artist GTA", desc: "Are you based in Berlin and interested in video games? Do you want to put rough German voices for our mafia characters? We are currently seeking German native voice actors in Frankfurt to provide video game voice over. Voice acting for video game voice over recording. Independently recording demo samples at home when considered for a role. Interpreting scripts, deciphering characters, following the instructions of an artistic director and delivering believable performances Requirements: Native German (Berlin). We know you're a tough young man and you can make it.", _type: "Internship", startDate: Date.new(2022,12,01), salary: 60000, city: nintendo.city, user_id: adi.id, employer_id: nintendo.id, companySize: "1000+", category: "Artist", onsite: "On-Site" })

  Job.create!({ title: "UI Artist (f/m/d)", desc: "As a Lead UI Artist, you will be responsible for establishing and driving the direction of UI Art. You will guide the UI Artists in delivering high quality assets and will provide ongoing support to grow the team.", _type: "Parttime", startDate: Date.new(2023,01,01), salary: 48000, city: activision.city, user_id: juan.id, employer_id: activision.id, companySize: "1000+", category: "Artist", onsite: "Remote" })

  Job.create!({ title: "Sound Designer - Diablo Immortal", desc: "As a Sound Designer, you’ll be work closely with the sound designers, game producers, and designers to bring their characters, creatures, and environments to life. Our Sound Designers are comfortable collaborating with various disciplines to create magical abilities, creatures, UI, VO and environmental audio that compliment and meld seamlessly with gameplay. In addition, each of our Sound Designers record and create original content while utilizing our proprietary game tools to integrate their work into the final product - ensuring that great concepts make the transition from the microphone to the game on the shelves.", _type: "Part-time", startDate: Date.new(2023,01,01), salary: 38000, city: ea.city, user_id: adi.id, employer_id: ea.id, companySize: "1000+", category: "Sound", onsite: "On-Site" })

  Job.create!({ title: "Graphics Developer (f/m/d)", desc: "Want to develop a cutting edge game engine that impacts millions of players around the world? Then come join our PES Team (Procedural Environment Systems) and develop graphics functionalities within the game engine with the goal of creating the best visuals possible!", _type: "Freelancer", startDate: Date.new(2023,01,15), salary: 52000, city: nintendo.city, user_id: aj.id, employer_id: nintendo.id, companySize: "1000+", category: "Developer", onsite: "Hybrid" })

  Job.create!({ title: "Gameplay Developer (f/m/d)", desc: "As part of Avatar: Frontiers of Pandora, you will play an instrumental role in bringing to life the beautiful and dangerous world of Pandora. This is a unique opportunity to keep growing your experience in games while working hand in hand with Disney's creative minds and James Cameron's production company, Lightstorm Entertainment.", _type: "Working Student", startDate: Date.new(2023,02,01), salary: 24000, city: activision.city, user_id: juan.id, employer_id: activision.id, companySize: "1000+", category: "Developer", onsite: "Remote" })

  Job.create!({ title: "Software Developer (f/m/d)", desc: "As a Software Developer, your primary objective is to lead a team of testers and work with developers, artists, and designers to ensure the quality and stability of new features and game content across multiple platforms (PC, PS4, Xbox One) while coordinating with various co-dev partners around the world.", _type: "Fulltime", startDate: Date.new(2022,12,01), salary: 50000, city: nintendo.city, user_id: hinnerk.id, employer_id: nintendo.id, companySize: "1000+", category: "Developer", onsite: "Remote" })

  Job.create!({ title: "AUDIO DESIGNER (f/m/d)", desc: "We are a thriving Community of top technology talent that is globally connected. We design and engineer the products and solutions of many brands that you know and love. No matter where you are on your digital career roadmap, we can help you grow and have fun while doing it. Let’s take this journey together!", _type: "Freelancer", startDate: Date.new(2022,12,01), salary: 50000, city: nintendo.city, user_id: hinnerk.id, employer_id: nintendo.id, companySize: "1000+", category: "Sound", onsite: "On-Site" })

  Job.create!({ title: "UI/UX Artist Designer", desc: "We are looking for a (Senior) UI/UX Designer to work on our hit game 'Idle Miner Tycoon'. You will be part of the IMT Team designing screens and flows, prototyping, and playtest to improve the user centric experience for a game with over 220 million downloads. Identify future features for the game in an agile and fast-paced environment by developing a deep comprehension of our player's needs and motivations using data, information from the players, and your own F2P knowledge.", _type: "Part-time", startDate: Date.new(2023,01,01), salary: 25000, city: nintendo.city, user_id: aj.id, employer_id: nintendo.id, companySize: "1000+", category: "Remote", onsite: "Artist" })

  Job.create!({ title: "Lead Sales Producer", desc: "As our new Lead Producer you will be responsible for one of the largest commercially successful games of Ubisoft with millions of concurrent players and a strong E-sport scene. Team-play, intense close quarters confrontations, tactics and explosive action are at the center of the experience for our players.",_type: "Freelancer", startDate: Date.new(2023,01,15), salary: 62000, city: activision.city, user_id: adi.id, employer_id: activision.id, companySize: "1000+", category: "Sales", onsite: "On-Site" })

  Job.create!({ title: "Senior Technical Level Engineer", desc: "A Senior Technical Level Engineer is a solution finder and liaison between level designers and other disciplines. They help with shaping the implementation details of complex locations; as well as, creating and integrating reusable location ingredients into the game themselves. They are advocates for production efficiency and quality for world creation by mentoring others and highlighting constraints.", _type: "Fulltime", startDate: Date.new(2023,02,01), salary: 57000, city: nintendo.city, user_id: juan.id, employer_id: nintendo.id, companySize: "1000+", category: "Engineer", onsite: "On-Site" })

  Job.create!({ title: "Intermediate Gameplay Developer", desc: "Join us in building the next great AAA title and see your code run on millions of devices across the world as we create a world for players to enjoy. As an Intermediate Gameplay Programmer, you will develop gameplay elements which facilitate the playability of the game and complex gameplay mechanisms.", _type: "Internship", startDate: Date.new(2023,02,01), salary: 42000, city: ubisoft.city, user_id: hinnerk.id, employer_id: ubisoft.id, companySize: "1000+", category: "Developer", onsite: "Hybrid" })

  Job.create!({ title: "Gameplay Developer [FAR CRY Project]", desc: "When you're a Gameplay Programmer at Ubisoft Toronto, you have direct influence over the quality of the game that will end up in the players' hands; there is a tangible link between your work and the player experience. You are entrusted with coding the interactive systems that make the game.", _type: "Fulltime", startDate: Date.new(2023,02,01), salary: 90000, city: activision.city, user_id: hinnerk.id, employer_id: activision.id, companySize: "1000+", category: "Developer", onsite: "On-Site" })

  Job.create!({ title: "Senior Artist Animator", desc:"The animation department is a small hub of creative and hardworking artists from many diverse backgrounds where professionalism, trust, and fun rub shoulders every day. The animation department is currently growing and looking to onboard new teammates. We are looking forward to new projects with new challenges and high-quality work deliveries.", _type: "Freelancer", startDate: Date.new(2023,02,01), salary: 43700, city: ea.city, user_id: aj.id, employer_id: ea.id, companySize: "1000+", category: "Artist", onsite: "Hybrid" })

  Job.create!({ title: "Roto Paint Artist", desc: "Paint out rigs and wires using Nuke and other relevant software", _type: "Part-time", startDate: Date.new(2023,02,01), salary: 36700, city: nintendo.city, user_id: adi.id, employer_id: nintendo.id, companySize: "1000+", category: "Artist", onsite: "On-site" })

  Job.create!({ title: "Generalist Developer [Rainbow Six Mobile]", desc:"As a Generalist Programmer, you are the Swiss Army knife of your project. You support wherever needed, able to adapt to any programming challenge thrown your way. You’ll contribute to anything from gameplay programming to crafting tools for the upcoming Rainbow Six Mobile, an ambitious AAA mobile game developed in partnership with teams around the world.", _type: "Working Student", startDate: Date.new(2023,02,01), salary: 15000, city: ubisoft.city, user_id: juan.id, employer_id: ubisoft.id, companySize: "1000+", category: "Developer", onsite: "On-Site" })

  Job.create!({ title:"C++ Developer [Snowdrop]", desc: "You put your C++ skills to work on any problem in need of a solution. Whether it’s working on productions built in Snowdrop or contributing to the engine itself, you’re there to support – able to adapt to any programming challenge thrown at the studio. Snowdrop is a powerful game engine that enables Ubisoft content creators to set their creative minds free. Fast and flexible, Snowdrop gives developers innovative tools designed from the ground up for creating the unknown. This engine will power upcoming titles like Avatar: Frontiers of Pandora, the Star Wars Project, and the newly announced Splinter Cell remake.", _type: "Working Student", startDate: Date.new(2023,02,01), salary: 10000, city: ubisoft.city, user_id: hinnerk.id, employer_id: ubisoft.id, companySize: "1000+", category: "Developer", onsite: "Hybrid" })

  Job.create!({ title: "Gameplay Artist Animator [Star Wars Project]", desc: "As a Gameplay Animator at Ubisoft Paris you will be working together with the team at Massive Entertainment to create a new story-driven open-world video game set in the Star Wars galaxy. Our goal is to create a game and a story that bring both new and lifelong fans on an immersive and outstanding journey, which will stay with them for years to come.", _type: "Freelancer", startDate: Date.new(2023,02,01), salary: 57000, city: ea.city, user_id: aj.id, employer_id: ea.id, companySize: "1000+", category: "Artist", onsite: "On-Site" })

  Job.create!({ title: "Web Developer", desc: "As part of our web development team, you will be involved in creating the latest features of our web applications as well as supporting the connected features of our games. Your tasks will range from front-end interface development, to debugging, to back-end service development. As a member of an agile team, your work will be done in close collaboration with our UX designers, game designers, and testers. In addition, you will research and identify the best solutions to the technical challenges we face on our journey and constantly discover new ways to improve our work methods.", _type: "Part-time", startDate: Date.new(2023,02,01), salary: 30000, city: ea.city, user_id: adi.id, employer_id: ea.id, companySize: "1000+", category: "Developer", onsite: "Remote" })

  Job.create!({ title: "Studio Sales Director", desc: "As a Production Director, you thrive on placing people at the core of all that you do. Your ability to naturally build rapport and harness relationships will enable you to effectively manage multiple stakeholders and ensure the continued success of our projects. You relish managing multiple projects and are driven by a sense of personal achievement.", _type: "Fulltime", startDate: Date.new(2023,02,01), salary: 55700, city: nintendo.city, user_id: juan.id, employer_id: nintendo.id, companySize: "1000+", category: "Sales", onsite: "On-Site" })

  Job.create!({ title: "Senior Associate Engineer [New IP]", desc: "As a Senior Associate Producer, you’ll thrive on facilitating the production of multiple core project features and activities using your project management skills and communicating effectively, across various teams.", _type: "Working Student", startDate: Date.new(2023,02,01), salary: 17800, city: ubisoft.city, user_id: juan.id, employer_id: ubisoft.id, companySize: "1000+", category: "Engineer", onsite: "On-Site" })

  Job.create!({ title: "Live Sales Coordinator", desc: "When you’re a Live Operations Coordinator at UbiTO, you’re responsible for the behind-the-scenes prep and posting of the news articles, free events, and promotions that go live on our digital distribution platform, Ubisoft Connect. As the primary point of contact for updating the platform, you plan ahead and publish on time; coordinating, communicating, and collaborating with teams across the company. You collect the information you need internally to share externally, all to ultimately connect players with content related to their favourite Ubisoft games on Ubisoft Connect.", _type: "Fulltime", startDate: Date.new(2023,02,01), salary: 57000, city: ea.city, user_id: aj.id, employer_id: ea.id, companySize: "1000+", category: "Sales", onsite: "Hybrid" })

  Job.create!({ title: "Vulnerability Management Engineer", desc: "As a Vulnerability Management Specialist, you will support the day-to-day vulnerability mitigation activities as well as efforts to implement best practice methods, processes, tools and drive continuous improvement initiatives at Ubisoft. You will be joining Ubisoft within the Security & Risk Management Department – SRM, which is a global team across Europe, Asia, and the Americas. In this role, you will act as a point of contact and facilitator for vulnerability management within Ubisoft’s SRM group. Acting as a bridge between SRM and Ubisoft as a whole, you’ll need to present insightful results in simple, yet, effective business terms.", _type: "Fulltime", startDate: Date.new(2023,02,01), salary: 99200, city: nintendo.city, user_id: adi.id, employer_id: nintendo.id, companySize: "1000+", category: "Engineer", onsite: "Remote" })

  Job.create!({ title: "Intern - Developer Support (6 months Internship)", desc: "This job position is to provide technical support to Ubisoft staff of Mumbai and Pune office on using their IT equipment’s. Be responsible for the evaluation, installation and maintenance of staff's computer hardware, software, networks and associated peripherals. Moreover, the person also participates in IT projects to improve users' productivity.", _type: "Internship", startDate: Date.new(2023,02,01), salary: 58000, city: activision.city, user_id: juan.id, employer_id: activision.id, companySize: "1000+", category: "Developer", onsite: "On-Site" })

  Job.create!({ title: "Sales Manager", desc: "Within i3D.net, the Project Manager is responsible for coordinating and supervising multiple projects simultaneously. The nature of the projects is diverse – you may oversee delivering dedicated servers to one of our customers while you’re also coordinating the build-up of a new PoP in one of our Freelancer data center locations. The Project Manager at i3D.net plays a true pivotal role. You will be working and communicating with every department in the company on a day-to-day basis.", _type: "Internship", startDate: Date.new(2023,02,01), salary: 20700, city: ubisoft.city, user_id: hinnerk.id, employer_id: ubisoft.id, companySize: "1000+", category: "Sales", onsite: "On-Site" })

  Job.create!({ title: "AI Developer", desc: "UBISOFT is seeking for AI Programmer having proficiency in C++, Scripting, and strong skills in AI technologies applied to video game programming. Good 3D mathematical skills are required. Interest in video games and knowledge of different video game consoles like Xbox One X/S, PlayStation 4, 5 and other cutting-edge game consoles would be an advantage (But not a requirement). As an AI Programmer you will be working with gameplay team to own at least one aspect of AI in a gameplay interaction system – designing, implementing, and polishing AI behaviors. Another responsibility of AI Programmer is to come up with Tooling solutions for Technical Design.", _type: "Part-time", startDate: Date.new(2023,02,01), salary: 28000, city: ea.city, user_id: aj.id, employer_id: ea.id, companySize: "1000+", category: "Developer", onsite: "Remote" })

  Job.create!({ title: "Technical Developer", desc: "As a technical architect at Ubisoft Montreal, you will build and maintain a technology ecosystem that facilitates the work of production teams so that they can invest their time and talent in what counts most: content creation.", _type: "Working Student", startDate: Date.new(2023,02,01), salary: 19000, city: nintendo.city, user_id: adi.id, employer_id: nintendo.id, companySize: "1000+", category: "Developer", onsite: "On-Site" })

  Job.create!({ title: "Intermediate Gameplay Developer", desc: "Join us in building the next great AAA title and see your code run on millions of devices across the world as we create a world for players to enjoy. As an Intermediate Gameplay Programmer, you will develop gameplay elements which facilitate the playability of the game and complex gameplay mechanisms.", _type: "Fulltime", startDate: Date.new(2023,02,01), salary: 57000, city: activision.city, user_id: juan.id, employer_id: activision.id, companySize: "1000+", category: "Developer", onsite: "Hybrid" })

  Job.create!({ title: "Intermediate C++ Engineer", desc: "We are looking for an Experienced C++ Developer to join our engine team. As a Game Engine Developer you will be on the front line of all dynamic and emerging technologies used to build AAA games, implementing new features and optimizing for various hardware architectures.", _type: "Working Student", startDate: Date.new(2023,02,01), salary: 17000, city: ubisoft.city, user_id: hinnerk.id, employer_id: ubisoft.id, companySize: "1000+", category: "Engineer", onsite: "Hybrid" })

  Job.create!({ title: "(Lead) R&D Scientist Engineer", desc: "As an R&D Scientist in La Forge China team, you will define our research direction within your own area of expertise, narrowing down our focus to topics that advance public knowledge and help to create world-class games and technologies. You will oversee and develop state-of-the-art prototypes that bring innovations to players and across the company, in domains such as virtual characters and behaviors, digital content creation or systemic environments to name a few.", _type: "Fulltime", startDate: Date.new(2023,02,01), salary: 52700, city: ea.city, user_id: aj.id, employer_id: ea.id, companySize: "1000+", category: "Engineer", onsite: "Remote" })

  Job.create!({ title: "Network Engineer", desc: "As a Network Engineer, you are part of the infrastructure operations team. This department is responsible for maintaining the global network of i3D.net and its internal servers. Primary work will be monitoring, maintaining, and upgrading the network. You manage or participate in projects and inform your direct colleagues about these projects so they can be delivered on time for our customers.", _type: "Fulltime", startDate: Date.new(2023,02,01), salary: 59500, city: nintendo.city, user_id: adi.id, employer_id: nintendo.id, companySize: "1000+", category: "Engineer", onsite: "On-Site" })

  Job.create!({ title: "Game Developer", desc: "We are looking for an experienced Game Designer to take good care of the balancing for our newest game’s systems and economy and work together with our core team based in Berlin. We accept remote only candidates but also support moving to Berlin.", _type: "Fulltime", startDate: Date.new(2023,02,01), salary: 77500, city: bethesda.city, user_id: juan.id, employer_id: bethesda.id, companySize: "201-500", category: "Developer", onsite: "On-Site" })

  Job.create!({ title: "Unity Game Engineer", desc: "As Unity Game Engineer, you will actively help to shape an exciting area of our company and you will be one of the driving forces in the development of games for our web platform. Together with members of our Product, Art, Backend, QA, Game Design as well as Marketing teams, you will create an...", _type: "Working Student", startDate: Date.new(2023,02,01), salary: 17500, city: santaMonica.city, user_id: adi.id, employer_id: santaMonica.id, companySize: "201-500", category: "Engineer", onsite: "Remote" })

  Job.create!({ title: "Senior Software Engineer", desc: "We are looking for a Senior Software Engineer who loves solving complex problems and has a passion for translating complex data into an intuitive UI experience.", _type: "Fulltime", startDate: Date.new(2023,02,01), salary: 17500, city: squareEnix.city, user_id: aj.id, employer_id: squareEnix.id, companySize: "1000+", category: "Engineer", onsite: "Remote" })

  Job.create!({ title: "Project Sound Director", desc: "As a Project Audio Director, you will collaborate with game directors and central audio teams to deliver AAA calibre audio solutions to our projects. You will lead the project audio development covering the planning, scopes, schedules, R&D, creative and technical developments, implementation, mixing, and optimisations. You will also be supporting the project requirements, vision and any franchise level initiatives and strategies.", _type: "Freelancer", startDate: Date.new(2023,02,01), salary: 17500, city: epicGames.city, user_id: hinnerk.id, employer_id: epicGames.id, companySize: "1000+", category: "Sound", onsite: "On-Site" })

  Job.create!({ title: "Senior 3D Artist PC and Console Game", desc: "We are working with a PC and console studio based in Germany, Berlin who is looking for a Senior 3D Artist to work on their hit project as well as their exciting new IPs. You will be creating a range of different types of 3D assets and props, and will need to be able to demonstrate a variety of art styles both realistic and cartoony.", _type: "Internship", startDate: Date.new(2023,02,01), salary: 99500, city: guerrilla.city, user_id: juan.id, employer_id: guerrilla.id, companySize: "201-500", category: "Artist", onsite: "On-Site" })

  Job.create!({ title: "Lead Game Engineer", desc: "We are partnering with an exciting AAA studio who are rapidly expanding their growth. They are looking for a Lead Game Designer to join their team on an unannounced AAA multiplayer title.", _type: "Internship", startDate: Date.new(2023,02,01), salary: 51500, city: industries.city, user_id: aj.id, employer_id: industries.id, companySize: "201-500", category: "Engineer", onsite: "Hybrid" })

  Job.create!({ title: "Game Economy Developer", desc: "We are partnering with an amazing games studio based in Frankfurt am Main, who are offering a fully remote position or the opportunity to relocate. You will be working on a new multi-platform multiplayer franchise (Shooter).", _type: "Freelancer", startDate: Date.new(2023,02,01), salary: 27500, city: bethesda.city, user_id: hinnerk.id, employer_id: bethesda.id, companySize: "201-500", category: "Developer", onsite: "On-Site" })

  Job.create!({ title: "Games Developer - AAA Racing", desc: "The ethos of this studio is based on working collectively with passionate staff, so they want someone who loves video games first and foremost, and lets this shine through in their attitude and their work. The right candidate will have demonstrable experience in similar positions and be able to communicate their qualities, and will ideally have worked on a high-profile console title in the past. This is a fantastic opportunity to work within a team that champions quality, and works collaboratively to ensure they meet the highest gaming standards.", _type: "Fulltime", startDate: Date.new(2023,02,01), salary: 97500, city: nintendo.city, user_id: adi.id, employer_id: nintendo.id, companySize: "1000+", category: "Developer", onsite: "Remote" })

  Job.create!({ title: "Principal Game Engineer", desc: "The ideal candidate will have experience of full development lifecycles on at least one AAA game title, and will be placed in charge of key areas of the game at every phase from its early development; a successful candidate will translate the game vision set by the Game Director into compelling experiences.", _type: "Internship", startDate: Date.new(2023,02,01), salary: 37504, city: guerrilla.city, user_id: juan.id, employer_id: guerrilla.id, companySize: "201-500", category: "Engineer", onsite: "On-Site" })

  Job.create!({ title: "Engineer of Game Production", desc: "Educator to join our faculty in support of our popular Game Production Management program embedded within Champlain's renowned Game Studio. The Stiller School's mission is to develop the strengths, integrity, expertise and entrepreneurial mindset of aspiring and innovative professionals to create positive change in their lives, workplaces, communities, and the world.", _type: "Working Student", startDate: Date.new(2023,02,01), salary: 10100, city: squareEnix.city, user_id: hinnerk.id, employer_id: squareEnix.id, companySize: "1000+", category: "Engineer", onsite: "Remote" })

  Job.create!({ title: "Mobile Game Developer", desc: "The successful candidate will be responsible for managing the teams, the execution and delivery of the project. Therefore, a strong experience of working in a game development role is essential. As a Mobile Game Producer, you will be managing all aspects of the production team, collaborating with other departments regarding in game features and updating the CEO and any stakeholders on the progress.", _type: "Freelancer", startDate: Date.new(2023,02,01), salary: 52501, city: epicGames.city, user_id: adi.id, employer_id: epicGames.id, companySize: "1000+", category: "Developer", onsite: "Hybrid" })

  Job.create!({ title: "Developer / Agile team coach", desc: "The Producer / Agile team coach is responsible for the efficient workings of a cross-disciplinary game development team at Fatshark. As a Producer / Agile team coach you will be an integral part of the team and also work closely - and effectively communicate - with product owners, directors and other teams at Fatshark. As a pragmatic servant-leader you will guide, lead and coach the team through all stages of development, focusing on how the team operates to deliver features and content in an efficient and sustainable way. ", _type: "Fulltime", startDate: Date.new(2023,02,01), salary: 60501, city: fatshark.city, user_id: juan.id, employer_id: fatshark.id, companySize: "51-200", category: "Developer", onsite: "On-site" })

  Job.create!({ title: "Build Engineer", desc: "As a full-time Build Engineer at Fatshark, you and the team will create, own, and develop the infrastructure of our build system, including build pipelines, CI/CD servers, and automation tools. We want to improve our way of building and deploying continuously, and you will be working closely together with our developers, QA, and release managers to take this team to the next level. At Fatshark, you will be a part of making the best co-op games in the industry.", _type: "Parttime", startDate: Date.new(2023,02,01), salary: 60501, city: fatshark.city, user_id: aj.id, employer_id: fatshark.id, companySize: "51-200", category: "Engineer", onsite: "Remote" })

  Job.create!({ title: "Lighting Artist", desc: "As a Lighting Artist at Fatshark you will be closely collaborating with another Lighting artist, concept and level art teams. Since we are using our own in-house engine Stingray, you would also have the opportunity to work with our Engine and Tools programmers to assist in developing new features in Engine for you and your fellow artists to use. Your main focus will be helping the World Art team during the process of developing new levels and environments by setting up shading environments, in-level lighting, color grading, and doing necessary optimization. You would be helping out Art direction with levels, but also Cinematics team with lighting when there is a new trailer coming out.", _type: "Freelancer", startDate: Date.new(2023,02,01), salary: 60501, city: fatshark.city, user_id: aj.id, employer_id: fatshark.id, companySize: "51-200", category: "Artist", onsite: "Hybrid" })

  Job.create!({ title: "Gameplay Artist Animator", desc: "We are looking for a talented and versatile Gameplay Animator to join our team! You will work with first person rigs as well as a wide range of Enemy characters to help develop exciting and visceral combat. The role will entail very close collaboration with Game Design and AI, a team where every member has a lot of responsibility and influence. You need to be flexible and creative and able to plan your work efficiently to meet deadlines.", _type: "Internship", startDate: Date.new(2023,02,01), salary: 60501, city: fatshark.city, user_id: aj.id, employer_id: fatshark.id, companySize: "51-200", category: "Artist", onsite: "On-site" })

  Job.create!({ title: "HR Sales Partner", desc: "As Human Resources Business Partner (HRBP) the objective is to support the business in both strategic planning as well as operational hands-on support for management and employees. The HRBP is responsible for bringing an HR perspective in people related policies and processes, including e.g. employer branding, work environment, motivation, retention, and legal compliance, all in accordance with the company values and goals. The HRBP works closely with the senior management team, managers/leaders, talent acquisition and office/HR admin.", _type: "Working Student", startDate: Date.new(2023,02,01), salary: 60501, city: fatshark.city, user_id: aj.id, employer_id: fatshark.id, companySize: "51-200", category: "Sales", onsite: "Remote" })

  Job.create!({ title: "UI Developer", desc: "Working as a UI programmer at Fatshark is a little bit different than at many other studios. We don't rely on third party UI libraries or dependencies like Scaleform, Qt, Flash, or HTML. Instead, our interfaces are completely programmatic and fully integrated in our gameplay code - which is written in the Lua scripting language. As a UI programmer you would be working as a part of the team on our released title Warhammer: Vermintide 2. Your main focus will be developing new feature sets. Taking initiative and coming up with creative solutions around the features you develop are relevant for this role and encouraged by the team.", _type: "Working Student", startDate: Date.new(2023,02,01), salary: 60501, city: fatshark.city, user_id: aj.id, employer_id: fatshark.id, companySize: "51-200", category: "Developer", onsite: "Hybrid" })

  Job.create!({ title: "Senior Concept Artist", desc: "As a Senior Concept Artist at Fatshark you will be a part of our talented Concept Team of 4 artists, producing concept art to support our production pipeline of 3D artists, both for in-house and outsourcing colleagues. Your responsibility will be the development of the upcoming 'Warhammer 40K Darktide' release. Your main focus will be to produce environment concepts, visually develop and lead the way for our inhouse World art department during the process of developing new levels and environments.", _type: "Internship", startDate: Date.new(2023,02,01), salary: 97503, city: redhook.city, user_id: adi.id, employer_id: redhook.id, companySize: "1-10", category: "Artist", onsite: "Hybrid" })

  Job.create!({ title: "Experienced Technical Artist Animator", desc: "As an Experienced Technical Animator you will take a central role in the character team. You will interact closely with Technical Art, Animation and Code to prototype new ideas as well as improve on existing pipeline, tools and systems. The role requires you to have experience in designing and developing an animation pipeline for game development in MotionBuilder. You are a problem solver and enjoy exploring new technical solutions. You will be in charge of creating high quality human and creature character rigs, both for motion capture data and hand key animation, along with facial animation setup and skinning.", _type: "Parttime", startDate: Date.new(2023,02,01), salary: 82522, city: redhook.city, user_id: hinnerk.id, employer_id: redhook.id, companySize: "1-10", category: "Artist", onsite: "On-site" })

  Job.create!({ title: "Technical Artist", desc: "We are looking for a Technical Artist to join our environment production team. You will work directly with our Technical Artists, Environment Artists and Programmers to create high quality and performant environments for our games. You will be responsible for shader development in our inhouse shader authoring tools, building functional environment assets and improving the environment art production pipeline.", _type: "Parttime", startDate: Date.new(2023,02,01), salary: 29522, city: redhook.city, user_id: hinnerk.id, employer_id: redhook.id, companySize: "1-10", category: "Artist", onsite: "Remote" })

  Job.create!({ title: ".NET Software Engineer", desc: "You will be given complete ownership of your business area and the opportunity to work on the full project life cycle. .NET Software Engineer applicants should have a skill set that encompasses: .NET, .NET Core / ASP.NET MVC, C# and SQL Server. Our client can provide with exposure to: .NET 7, Azure, Angular 14, Solid, DRY, LINQ, multithreading, Microservices, RESTful, Web API 2, JavaScript, HTML5, Agile and SQL Server 2022.", _type: "Working Student", startDate: Date.new(2023,02,01), salary: 85030, city: redhook.city, user_id: hinnerk.id, employer_id: redhook.id, companySize: "1-10", category: "Engineer", onsite: "On-site" })

  Job.create!({ title: "Sound Engineering", desc: "We are looking for a talented Game Engineer with Unreal skills and experience in audio engineering to join the team behind The Cycle, a F2P multiplayer shooter packed with innovation. You will join in an exciting development phase and be part of an experienced team that has a lot to offer and encourages you to grow with us together!", _type: "Parttime", startDate: Date.new(2023,02,01), salary: 39002, city: redhook.city, user_id: hinnerk.id, employer_id: redhook.id, companySize: "1-10", category: "Sound", onsite: "Hybrid" })

  Job.create!({ title: "German Sales Service Representative", desc: "Are you a tech-savvy and game lover with a passion for helping people? Do you speak German? This is a great opportunity for German speakers to work at a fantastic multinational consumer electronics and video game company.", _type: "Internship", startDate: Date.new(2023,02,01), salary: 50521, city: redhook.city, user_id: hinnerk.id, employer_id: redhook.id, companySize: "1-10", category: "Sales", onsite: "Remote" })

  Job.create!({ title: "Online Sales Manager", desc: "Collaboration in the creation of integrated marketing concepts and communication campaigns for national as well as international marketing", _type: "Fulltime", startDate: Date.new(2023,02,01), salary: 28000, city: ea.city, user_id: aj.id, employer_id: ea.id, companySize: "1000+", category: "Sales", onsite: "Hybrid" })

  Job.create!({ title: "Senior Artist Animator", desc: "We are looking for a talented and experienced Technical Animator to come join our team and develop amazing games with us. We’re looking for talented professionals who love working in interdisciplinary teams in a fast-paced and creative environment. The technical animator’s primary mission is to rig characters, solve technical production issues, streamline processes and develop tools and frameworks for character animation.", _type: "Fulltime", startDate: Date.new(2023,02,01), salary: 17000, city: ubisoft.city, user_id: hinnerk.id, employer_id: ubisoft.id, companySize: "1000+", category: "Artist", onsite: "On-site" })

  Job.create!({ title: "Senior Sales Producer [New IP]", desc: "As a Senior Associate Producer, you’ll thrive on facilitating the production of multiple core project features and activities using your project management skills and communicating effectively, across various teams.", _type: "Internship", startDate: Date.new(2023,02,01), salary: 17802, city: ubisoft.city, user_id: juan.id, employer_id: ubisoft.id, companySize: "1000+", category: "Sales", onsite: "Remote" })

  Job.create!({ title: "Senior Frontend Engineer", desc: "We are looking for a seasoned web frontend engineer to join our team remotely and help us take our online games to the next level! As a Senior Frontend Engineer, you would be working directly on the codebase of our games and take part in a challenging, sprawling project to design, revamp and rewrite frontend functionality into a new, unreleased mobile version of the backbone of our games using a pure web stack. Javascript/Browser performance will be tested and pushed, as we aim for an UX that feels fluid, responsive and native-like, while sticking to a strict web stack.", _type: "Freelancer", startDate: Date.new(2023,02,01), salary: 67802, city: ubisoft.city, user_id: juan.id, employer_id: ubisoft.id, companySize: "1000+", category: "Engineer", onsite: "Hybrid" })

  Job.create!({ title: "Sales Intern", desc: "We are looking for a motivated and enthusiastic individual to join our team as a Marketing Intern (m/f/d) to help us launch new titles across Europe and expand the reach of our Summoners War brand. This internship is intended for a minimum of three to six months. The position is based in Berlin, Germany, and is available immediately. ", _type: "Working Student", startDate: Date.new(2023,02,01), salary: 19000, city: nintendo.city, user_id: adi.id, employer_id: nintendo.id, companySize: "1000+", category: "Sales", onsite: "Hybrid" })

  Job.create!({ title: "Senior Game Engineer", desc: "Would you like to leave a mark in the landscape of games while working in a fast-paced and hyper-creative environment and with people who are passionate to create an awesome game experience together? We are looking for a talented and experienced Senior Game Engineer to join YAGER's talented team. As Senior Game Engineer you are expected to work independently as well as to help our juniors to develop and grow. You will be part of an experienced team that has a lot to offer and encourages you to grow with us together!", _type: "Fulltime", startDate: Date.new(2023,02,01), salary: 77500, city: bethesda.city, user_id: juan.id, employer_id: bethesda.id, companySize: "201-500", category: "Engineer", onsite: "Remote" })

  Job.create!({ title: "Senior Technical Artist", desc: "We are currently seeking an experienced Technical Artist to support our team working on our next hit The Cycle: Frontier, a F2P multiplayer shooter packed with innovation. You will join in an exciting development phase and be part of an experienced team that has a lot to offer and encourages you to grow with us together! We’re looking for someone who is excited to work on something truly unique that will leave a hallmark in the landscape of online shooter games. As a Technical Artist, you are someone who loves solving complex technical problems to push the artistic possibilities. Your primary duties, under the direction of the Lead Technical Artist are in leading the technical art team in making the game look great, perform great and making our tools and pipelines great.", _type: "Parttime", startDate: Date.new(2023,02,01), salary: 77400, city: bethesda.city, user_id: juan.id, employer_id: bethesda.id, companySize: "201-500", category: "Artist", onsite: "On-Site" })

  Job.create!({ title: "Junior Artist Designer:in (UX/UI)", desc: "Intuitive user interfaces and a smooth user experience are as essential to our mobile games as their code. That's why you work as a product designer (UI/UX) together with the development team on the success of our games. Not only are you responsible for the entire product design, but you also design the entire Lotum world across a wide variety of design disciplines, from corporate design to social media. Would you like to inspire millions of people with your work?", _type: "Freelancer", startDate: Date.new(2023,02,01), salary: 73300, city: bethesda.city, user_id: juan.id, employer_id: bethesda.id, companySize: "201-500", category: "Artist", onsite: "Remote" })

  Job.create!({ title: "Influencer Sales Manager", desc: "We are looking for a motivated and enthusiastic individual to join our team as an Influencer Marketing Manager (m/f/d) to help us launch new titles across Europe and expand the reach of our Summoners War brand. The position is based in Berlin, Germany, and available immediately full-time or part-time.", _type: "Fulltime", startDate: Date.new(2023,02,01), salary: 97501, city: bethesda.city, user_id: juan.id, employer_id: bethesda.id, companySize: "201-500", category: "Sales", onsite: "On-Site" })

  Job.create!({ title: "Senior Unreal Engine Technical Artist", desc: "We know that Tech-Art covers a wide area, so we don’t expect you to be an expert in all skills listed below. If you have a specialization, are passionate about what you do, like to learn new things, and want to work with a team of professionals, most of which worked together for a long time already, we are happy to receive your application!", _type: "Internship", startDate: Date.new(2023,02,01), salary: 18500, city: bethesda.city, user_id: juan.id, employer_id: bethesda.id, companySize: "201-500", category: "Sales", onsite: "Hybrid" })

  Job.create!({ title: "Sales Account Manager", desc: "Contact our VIP players around the world and bring Community Management to the next level. If you love to communicate with premium customers, have a strong passion about gaming and bring the creativity to build up concepts to fully engage our most valuable players, then you might be the person we are looking for. Join us as an in-house VIP Account Manager for our games at the next possible start date.", _type: "Fulltime", startDate: Date.new(2023,02,01), salary: 89500, city: guerrilla.city, user_id: juan.id, employer_id: guerrilla.id, companySize: "201-500", category: "Sales", onsite: "On-Site" })

  Job.create!({ title: "Technical Artist (f/m/d)", desc: "Are you looking for a challenging job in an attractive work environment in the gaming industry? Do you want to use your creativity and artistic talent to create games that will be played by people all over the world? Then contribute to the success story of HandyGames™ and take the opportunity to work for one of Germany’s top game developers and publishers! We are looking for a Technical Artist (f/m/d) with creative ideas and good knowledge in the field of game development for our headquarters in Berlin, Germany.", _type: "Parttime", startDate: Date.new(2023,02,01), salary: 99000, city: guerrilla.city, user_id: juan.id, employer_id: guerrilla.id, companySize: "201-500", category: "Artist", onsite: "Remote" })

  Job.create!({ title: "Level Artist/Environment Artist", desc: "Are you looking for a challenging job in an attractive work environment in the gaming industry? Do you want to use your creativity and artistic talent to create games that will be played by people all over the world? Then contribute to the success story of HandyGames™ and take the opportunity to work for one of Germany’s top game developers and publishers! We are looking for an Environment Artist (f/m/d) with creative ideas and good knowledge in the field of game development for our headquarters in Berlin Germany.", _type: "Freelancer", startDate: Date.new(2023,02,01), salary: 55400, city: guerrilla.city, user_id: juan.id, employer_id: guerrilla.id, companySize: "201-500", category: "Artist", onsite: "Hybrid" })

  Job.create!({ title: "Sales Manager", desc: "At our headquarters in Worms, Germany, we are looking for a (Senior) Marketing Manager (m/f/d) to manage international marketing campaigns.", _type: "Internship", startDate: Date.new(2023,02,01), salary: 49500, city: guerrilla.city, user_id: juan.id, employer_id: guerrilla.id, companySize: "201-500", category: "Sales", onsite: "On-Site" })

  Job.create!({ title: "Technical Developer", desc: "At Paladin, we want to create games that make  you smile. Our goal is to create high-quality, wholesome games that have a positive impact on people. Now, Paladin is looking for a Technical Designer. Your responsibility is to design and prototype new ideas. You have a knack for game feel, and know how to polish the gameplay experience. Within the team you bridge design and tech, ensuring a well-oiled, tight-knit and highly productive team.", _type: "Working Student", startDate: Date.new(2023,02,01), salary: 39500, city: guerrilla.city, user_id: juan.id, employer_id: guerrilla.id, companySize: "201-500", category: "Developer", onsite: "Remote" })

  Job.create!({ title: "Senior Game Developer", desc: "As a Producer you’ll be in charge of translating the product roadmap into tangible features that add player value to our games. You will be the one with an overview on our multidisciplinary teams, making sure that everyone is able to do their best work. Besides being focused on internal communication streams, you will also be in direct contact with publishers and platform holders.", _type: "Working Student", startDate: Date.new(2023,02,01), salary: 29222, city: guerrilla.city, user_id: juan.id, employer_id: guerrilla.id, companySize: "201-500", category: "Developer", onsite: "Hybrid" })
  puts "Jobs created!"

  Job.create!({ title: "Web/Mobile Developer", desc: "At Lotum we design, develop and operate mobile games for Android, iOS and Facebook. Our goal is to work in small teams to create meaningful products that millions of friends and families play together every day. Our games like 4 Pics 1 Word and Quiz Planet have already been installed in 27 languages by more than 800 million users worldwide. Would you like to be part of our success and inspire people around the world with your work?", _type: "Parttime", startDate: Date.new(2023,02,01), salary: 44500, city: squareEnix.city, user_id: aj.id, employer_id: squareEnix.id, companySize: "1000+", category: "Developer", onsite: "On-site" })

  Job.create!({ title: "Working Student* Development", desc: "We are Gameforge, one of the leading publishers of free-to-play online games based in Berlin, Germany. Development Services expands our browser games and integrates new games into our portfolio. Our tasks cover a lot of different topics, ranging from third-level support, game client updates, to full-fledged feature implementations. Are you passionate about gaming and would you like to help us improve and run our games? With us, you can go straight into practice parallel to your studies.", _type: "Freelancer", startDate: Date.new(2023,02,01), salary: 33501, city: squareEnix.city, user_id: aj.id, employer_id: squareEnix.id, companySize: "1000+", category: "Developer", onsite: "Remote" })

  Job.create!({ title: "International Sales Contractor", desc: "The International Marketing Contractor will focus on growing Jackbox Games’ audience in Germany. The person in this role will be charged with growing our digital presence in Germany through the development of Deutsche-language social media channels and consistent website and email content. The International Marketing Contractor needs to have their finger on the pulse of gaming and entertainment culture in Germany and help us identify content, partnerships, and events of interest that can help us achieve our growth goals.", _type: "Internship", startDate: Date.new(2023,02,01), salary: 27500, city: squareEnix.city, user_id: aj.id, employer_id: squareEnix.id, companySize: "1000+", category: "Sales", onsite: "Hybrid" })

  Job.create!({ title: "Build Engineer (f/m/d)", desc: "We are currently looking for an experienced Build Engineer preferably with Unreal Engine experience to work with us on our new IP. We’re looking for someone who is excited to work on something truly unique that will leave a hallmark in the landscape of online shooter games. You will be part of an experienced team that has a lot to offer and encourages you to grow with us together! As a Build Engineer, you would join our company-wide Build-Engine team supporting multiple projects. Your focus would be working on game-centric build tooling and automation implementations while you would also touch base with our deployment solutions.", _type: "Working Student", startDate: Date.new(2023,02,01), salary: 66500, city: squareEnix.city, user_id: aj.id, employer_id: squareEnix.id, companySize: "1000+", category: "Engineer", onsite: "On-site" })

  Job.create!({ title: "Sales Account Manager (m/f/d)", desc: "HandyGames™ is part of the THQ Nordic and Embracer Group family and operates as an international publisher and developer for a worldwide audience. Communication and Games are your passion? You see your professional future in sales? You want to cooperate with partners around the world and work closely with an international and diverse team with an outstanding portfolio of games? As part of the sales and submission team of HandyGames™ in our headquarters in Berlin or Frankfurt/Germany you are responsible for the wellbeing of our global distribution partners.", _type: "Fulltime", startDate: Date.new(2023,02,01), salary: 77500, city: squareEnix.city, user_id: aj.id, employer_id: squareEnix.id, companySize: "1000+", category: "Sales", onsite: "Remote" })

  Job.create!({ title: "Unreal Engine Engineer (m/f/d)", desc: "Nine Worlds Studios is a new video game development studio under the roof of Kalypso Media Group. Our experienced founding team is based in Berlin or Frankfurt, Germany, where we work on internationally acclaimed IPs, and create fresh and innovative titles for consoles and PC. Currently, we are working on the next installment of the beloved strategy series Tropico and we are looking for developers with passion, team spirit and who work to a high standard to create remarkable games for players worldwide.", _type: "Parttime", startDate: Date.new(2023,02,01), salary: 96500, city: squareEnix.city, user_id: aj.id, employer_id: squareEnix.id, companySize: "1000+", category: "Engineer", onsite: "Hybrid" })

  Job.create!({ title: "Senior Game Developer (m/f/d)", desc: "We are currently looking for a Senior Game Designer (m/w/d). to support our new project based on the Commandos franchise. Claymore Game Studios are located in Darmstadt close to the Frankfurt-Rhine-Main area. We are working on the next installment of the internationally acclaimed Commandos franchise for PC and the latest generation of consoles. We are looking for passionate developers to join our team and actively define the future of one of the most iconic series in tactical strategy gaming.", _type: "Freelancer", startDate: Date.new(2023,02,01), salary: 43500, city: squareEnix.city, user_id: aj.id, employer_id: squareEnix.id, companySize: "1000+", category: "Developer", onsite: "On-site" })

  Job.create!({ title: "IT Engineer In-house (f/m/d)", desc: "We are currently seeking a talented and passionate IT-Admin (f/m/d) to support our In-house team. You will join a motivated and experienced team that has a lot to offer and encourages you to grow with us together! The ideal candidate is an admin who has extensive experience working on Windows OS environments (Desktop and Server) and an excellent understanding of computer hardware in general (Intel x86 architecture).", _type: "Internship", startDate: Date.new(2023,02,01), salary: 38500, city: squareEnix.city, user_id: aj.id, employer_id: squareEnix.id, companySize: "1000+", category: "Engineer", onsite: "Remote" })

  Job.create!({ title: "Senior Combat Developer (f/m/d)", desc: "We are currently seeking an experienced and passionate Senior Combat Designer to work with us on our flagship title ‘The Cycle’. Join us and be a driving force in Game Design to make the player combat experience shine and feel both challenging and satisfying. We’re looking for someone who is passionate about polishing the intricacies of gunplay, abilities and player movement to craft something truly unique that will leave a hallmark in the landscape of online shooter games. Be part of a tight-knit cross-disciplinary implementation team who are all passionate FPS gamers, take part in design discussions across the board, take part in the fun! We endorse being open-minded, always challenging our gameplay and testing new ideas and concepts to enrich it further. Developing a live game means we work in a fast-paced professional environment with rapid iteration – we “fail-fast” and then get up again.", _type: "Working Student", startDate: Date.new(2023,02,01), salary: 29700, city: squareEnix.city, user_id: aj.id, employer_id: squareEnix.id, companySize: "1000+", category: "Developer", onsite: "Hybrid" })

  Job.create!({ title: "Influencer Sales Manager", desc: "We are looking for a motivated and enthusiastic individual to join our team as an Influencer Marketing Manager (m/f/d) to help us launch new titles across Europe and expand the reach of our Summoners War brand. The position is based in Berlin, Germany, and available immediately full-time or part-time.", _type: "Fulltime", startDate: Date.new(2023,02,01), salary: 92501, city: riotGames.city, user_id: juan.id, employer_id: riotGames.id, companySize: "1000+", category: "Sales", onsite: "Remote" })

  Job.create!({ title: "Senior Unreal Engine Technical Artist", desc: "We know that Tech-Art covers a wide area, so we don’t expect you to be an expert in all skills listed below. If you have a specialization, are passionate about what you do, like to learn new things, and want to work with a team of professionals, most of which worked together for a long time already, we are happy to receive your application!", _type: "Internship", startDate: Date.new(2023,02,01), salary: 20520, city: santaMonica.city, user_id: adi.id, employer_id: santaMonica.id, companySize: "201-500", category: "Sales", onsite: "On-site" })

  Job.create!({ title: "Sales Account Manager", desc: "Contact our VIP players around the world and bring Community Management to the next level. If you love to communicate with premium customers, have a strong passion about gaming and bring the creativity to build up concepts to fully engage our most valuable players, then you might be the person we are looking for. Join us as an in-house VIP Account Manager for our games at the next possible start date.", _type: "Fulltime", startDate: Date.new(2023,02,01), salary: 89200, city: industries.city, user_id: juan.id, employer_id: industries.id, companySize: "201-500", category: "Sales", onsite: "Remote" })

  Job.create!({ title: "Technical Artist (f/m/d)", desc: "Are you looking for a challenging job in an attractive work environment in the gaming industry? Do you want to use your creativity and artistic talent to create games that will be played by people all over the world? Then contribute to the success story of HandyGames™ and take the opportunity to work for one of Germany’s top game developers and publishers! We are looking for a Technical Artist (f/m/d) with creative ideas and good knowledge in the field of game development for our headquarters in Berlin, Germany.", _type: "Parttime", startDate: Date.new(2023,02,01), salary: 92000, city: redhook.city, user_id: aj.id, employer_id: redhook.id, companySize: "1-10", category: "Artist", onsite: "Hybrid" })

  Job.create!({ title: "Level Artist/Environment Artist", desc: "Are you looking for a challenging job in an attractive work environment in the gaming industry? Do you want to use your creativity and artistic talent to create games that will be played by people all over the world? Then contribute to the success story of HandyGames™ and take the opportunity to work for one of Germany’s top game developers and publishers! We are looking for an Environment Artist (f/m/d) with creative ideas and good knowledge in the field of game development for our headquarters in Berlin Germany.", _type: "Fulltime", startDate: Date.new(2023,02,01), salary: 15400, city: santaMonica.city, user_id: aj.id, employer_id: santaMonica.id, companySize: "201-500", category: "Artist", onsite: "Remote" })

  Job.create!({ title: "Sales Manager", desc: "At our headquarters in Worms, Germany, we are looking for a (Senior) Marketing Manager (m/f/d) to manage international marketing campaigns.", _type: "Internship", startDate: Date.new(2023,02,01), salary: 29500, city: santaMonica.city, user_id: juan.id, employer_id: santaMonica.id, companySize: "201-500", category: "Sales", onsite: "Remote" })

  Job.create!({ title: "Technical Developer", desc: "At Paladin, we want to create games that make  you smile. Our goal is to create high-quality, wholesome games that have a positive impact on people. Now, Paladin is looking for a Technical Designer. Your responsibility is to design and prototype new ideas. You have a knack for game feel, and know how to polish the gameplay experience. Within the team you bridge design and tech, ensuring a well-oiled, tight-knit and highly productive team.", _type: "Working Student", startDate: Date.new(2023,02,01), salary: 29500, city: santaMonica.city, user_id: juan.id, employer_id: santaMonica.id, companySize: "201-500", category: "Developer", onsite: "Remote" })

  Job.create!({ title: "Network Engineer", desc: "As a Network Engineer, you are part of the infrastructure operations team. This department is responsible for maintaining the global network of i3D.net and its internal servers. Primary work will be monitoring, maintaining, and upgrading the network. You manage or participate in projects and inform your direct colleagues about these projects so they can be delivered on time for our customers.", _type: "Parttime", startDate: Date.new(2023,02,01), salary: 39500, city: squareEnix.city, user_id: adi.id, employer_id: squareEnix.id, companySize: "1000+", category: "Engineer", onsite: "Hybrid" })

  Job.create!({ title: "Game Developer", desc: "We are looking for an experienced Game Designer to take good care of the balancing for our newest game’s systems and economy and work together with our core team based in Berlin. We accept remote only candidates but also support moving to Berlin.", _type: "Fulltime", startDate: Date.new(2023,02,01), salary: 45500, city: fatshark.city, user_id: juan.id, employer_id: fatshark.id, companySize: "51-200", category: "Developer", onsite: "Remote" })

  Job.create!({ title: "Unity Game Engineer", desc: "As Unity Game Engineer, you will actively help to shape an exciting area of our company and you will be one of the driving forces in the development of games for our web platform. Together with members of our Product, Art, Backend, QA, Game Design as well as Marketing teams, you will create an...", _type: "Fulltime", startDate: Date.new(2023,02,01), salary: 17500, city: epicGames.city, user_id: adi.id, employer_id: epicGames.id, companySize: "1000+", category: "Engineer", onsite: "On-site" })

  Job.create!({ title: "Senior Software Engineer", desc: "We are looking for a Senior Software Engineer who loves solving complex problems and has a passion for translating complex data into an intuitive UI experience.", _type: "Internship", startDate: Date.new(2023,02,01), salary: 17500, city: redhook.city, user_id: aj.id, employer_id: redhook.id, companySize: "1-10", category: "Engineer", onsite: "Hybrid" })

  Job.create!({ title: "Project Sound Director", desc: "As a Project Audio Director, you will collaborate with game directors and central audio teams to deliver AAA calibre audio solutions to our projects. You will lead the project audio development covering the planning, scopes, schedules, R&D, creative and technical developments, implementation, mixing, and optimisations. You will also be supporting the project requirements, vision and any franchise level initiatives and strategies.", _type: "Parttime", startDate: Date.new(2023,02,01), salary: 38500, city: industries.city, user_id: hinnerk.id, employer_id: industries.id, companySize: "201-500", category: "Sound", onsite: "Hybrid" })

  Job.create!({ title: "Senior 3D Artist PC and Console Game", desc: "We are working with a PC and console studio based in Germany, Berlin who is looking for a Senior 3D Artist to work on their hit project as well as their exciting new IPs. You will be creating a range of different types of 3D assets and props, and will need to be able to demonstrate a variety of art styles both realistic and cartoony.", _type: "Fulltime", startDate: Date.new(2023,02,01), salary: 99500, city: fatshark.city, user_id: juan.id, employer_id: fatshark.id, companySize: "51-200", category: "Artist", onsite: "Remote" })

  Job.create!({ title: "Lead Game Engineer", desc: "We are partnering with an exciting AAA studio who are rapidly expanding their growth. They are looking for a Lead Game Designer to join their team on an unannounced AAA multiplayer title.", _type: "Working Student", startDate: Date.new(2023,02,01), salary: 31510, city: guerrilla.city, user_id: aj.id, employer_id: guerrilla.id, companySize: "201-500", category: "Engineer", onsite: "On-site" })

  Job.create!({ title: "Game Economy Developer", desc: "We are partnering with an amazing games studio based in Frankfurt am Main, who are offering a fully remote position or the opportunity to relocate. You will be working on a new multi-platform multiplayer franchise (Shooter).", _type: "Internship", startDate: Date.new(2023,02,01), salary: 17500, city: santaMonica.city, user_id: hinnerk.id, employer_id: santaMonica.id, companySize: "201-500", category: "Developer", onsite: "On-Site" })

  Job.create!({ title: "Games Developer - AAA Racing", desc: "The ethos of this studio is based on working collectively with passionate staff, so they want someone who loves video games first and foremost, and lets this shine through in their attitude and their work. The right candidate will have demonstrable experience in similar positions and be able to communicate their qualities, and will ideally have worked on a high-profile console title in the past. This is a fantastic opportunity to work within a team that champions quality, and works collaboratively to ensure they meet the highest gaming standards.", _type: "Working Student", startDate: Date.new(2023,02,01), salary: 97220, city: redhook.city, user_id: adi.id, employer_id: redhook.id, companySize: "1-10", category: "Developer", onsite: "Hybrid" })

  Job.create!({ title: "Senior Game Engineer", desc: "Would you like to leave a mark in the landscape of games while working in a fast-paced and hyper-creative environment and with people who are passionate to create an awesome game experience together? We are looking for a talented and experienced Senior Game Engineer to join YAGER's talented team. As Senior Game Engineer you are expected to work independently as well as to help our juniors to develop and grow. You will be part of an experienced team that has a lot to offer and encourages you to grow with us together!", _type: "Internship", startDate: Date.new(2023,02,01), salary: 71511, city: industries.city, user_id: juan.id, employer_id: industries.id, companySize: "201-500", category: "Engineer", onsite: "Hybrid" })

  Job.create!({ title: "Senior Technical Artist", desc: "We are currently seeking an experienced Technical Artist to support our team working on our next hit The Cycle: Frontier, a F2P multiplayer shooter packed with innovation. You will join in an exciting development phase and be part of an experienced team that has a lot to offer and encourages you to grow with us together! We’re looking for someone who is excited to work on something truly unique that will leave a hallmark in the landscape of online shooter games. As a Technical Artist, you are someone who loves solving complex technical problems to push the artistic possibilities. Your primary duties, under the direction of the Lead Technical Artist are in leading the technical art team in making the game look great, perform great and making our tools and pipelines great.", _type: "Fulltime", startDate: Date.new(2023,02,01), salary: 27400, city: riotGames.city, user_id: juan.id, employer_id: riotGames.id, companySize: "201-500", category: "Artist", onsite: "Remote" })

  Job.create!({ title: "Junior Artist Designer:in (UX/UI)", desc: "Intuitive user interfaces and a smooth user experience are as essential to our mobile games as their code. That's why you work as a product designer (UI/UX) together with the development team on the success of our games. Not only are you responsible for the entire product design, but you also design the entire Lotum world across a wide variety of design disciplines, from corporate design to social media. Would you like to inspire millions of people with your work?", _type: "Fulltime", startDate: Date.new(2023,02,01), salary: 23300, city: santaMonica.city, user_id: juan.id, employer_id: santaMonica.id, companySize: "201-500", category: "Artist", onsite: "Hybrid" })

  Job.create!({ title: "Influencer Sales Manager", desc: "We are looking for a motivated and enthusiastic individual to join our team as an Influencer Marketing Manager (m/f/d) to help us launch new titles across Europe and expand the reach of our Summoners War brand. The position is based in Berlin, Germany, and available immediately full-time or part-time.", _type: "Working Student", startDate: Date.new(2023,02,01), salary: 17501, city: ubisoft.city, user_id: juan.id, employer_id: ubisoft.id, companySize: "1000+", category: "Sales", onsite: "Remote" })

  jobs = Job.all

puts "Creating applications..."
  Application.create!({ user_id: users[0].id, job_id: jobs[0].id, employer_id: employers[0].id })
  Application.create!({ user_id: users[1].id, job_id: jobs[2].id, employer_id: employers[1].id })
  Application.create!({ user_id: users[2].id, job_id: jobs[4].id, employer_id: employers[2].id })
  Application.create!({ user_id: users[3].id, job_id: jobs[6].id, employer_id: employers[3].id })
puts "Applications created!"

puts "Creating Events..."
  Event.create!({ user_id: users[0].id, title: "Clash of Nerds", desc: "Backstage Beat 'Em Hub! Chilled & Casual Gaming Sesh at Sisyfass after an amazing year. Anyone who wants to just meet up, chat and have some drinks while enjoying some chilled gaming, come by!.", date: DateTime.new(2022, 12, 8, 7, 10, 9), venue: "Sisyfass", address: "Wildenbruchstr. 7, 12045 Berlin" })

  Event.create!({ user_id: users[1].id, title: "Nerdistan Arcade Bash", desc: "Retro gaming stations, arcade machines, tournament, drinks and old school nerding served as always with great vibes. The event starts at 19.00, tournament starts at 21.00. ", date: DateTime.new(2022, 12, 07, 7, 10, 9), venue: "Alte Kantine", address: "Knaackstraße 97, 10435 Berlin" })

  Event.create!({ user_id: users[2].id, title: "Game Creators Hangout", desc: "Es ist Zeit für einen Game Creators Hangout ! Der Game Creators Hangout ist ein Ort, an dem sich Spieleschaffende treffen, um über Spiele, das Leben und das Universum zu sinieren.", date: DateTime.new(2022, 12, 07, 7, 10, 9), venue: "12 Aetherloge", address: "Frankfurter Allee 26, 10247 Berlin"  })

  Event.create!({ user_id: users[3].id, title: "Nerd beer night", desc: "Do you like to learn about nerdy topics? What is artificial intelligence, and where is it headed? Are we alone in the universe, or are there other forms of life out there (Fermi paradox)? What is the state of the art in quantum computing?", date: DateTime.new(2022, 12, 07, 7, 10, 9), venue: "The Castle Berlin Mitte", address: "Invalidenstraße 129, 10115 Berlin"  })

  Event.create!({ user_id: users[3].id, title: "Digital Media Women Winter Meetup", desc: "wir wollen das Jahr noch einmal mit euch gemeinsam abschließen, an der frischen Luft und in Bewegung. Und ganz in Vorweihnachtsstimmung haben auch die eine oder andere kleine Überraschung für euch im Gepäck.", date: DateTime.new(2022, 12, 07, 7, 10, 9), venue: "Berlin Cathedral", address: "Am Lustgarten, Berlin"  })

puts "Events created!"


puts "Database seeded!"
